title: Logs
description: hidakatsuya's diary, notes, etc

baseurl: ""
url: ""

show_experts: false
header_pages:
  - about-me.md

minima:
  social_links:
    twitter: hidakatsuya
    github: hidakatsuya

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
