title: logs
description: Tech and life logs, my profile, etc

baseurl: ""
url: "https://hidakatsuya.dev"

timezone: Asia/Tokyo

google_analytics: UA-27955104-4

remote_theme: pages-themes/primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji

relative_links:
  collections: true

markdown: CommonMarkGhPages
commonmark:
  extensions:
    - autolink
    - strikethrough
    - table
