title: logs
description: Tech note, Profile, Diary, etc

baseurl: ""
url: ""

timezone: Asia/Tokyo

google_analytics: UA-27955104-4
show_experts: false
header_pages:
  - about-me.md

minima:
  social_links:
    twitter: hidakatsuya
    github: hidakatsuya
    stackoverflow: "1160252"

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-relative-links

relative_links:
  collections: true
